# Generated by Django 4.1.7 on 2023-03-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('uemail', models.EmailField(max_length=255)),
                ('upass', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
