# Generated by Django 4.1.7 on 2023-03-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placename', models.CharField(max_length=255)),
                ('number_of_visitors', models.EmailField(max_length=255)),
                ('time_slot', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
