# Generated by Django 4.1.7 on 2023-03-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_visitors',
            field=models.IntegerField(max_length=255),
        ),
    ]
